// src/lib/utils/cn.js
/**
 * cn
 * Joins a variadic list of class names while skipping falsy values. Mirrors the
 * helper generated by the Shadcn UI CLI without introducing extra dependencies.
 *
 * @param {...(string|false|null|undefined)} classes - Candidate class names.
 * @returns {string} Combined class string.
 */
export function cn(...classes) {
  return classes.filter(Boolean).join(" ");
}
