name: Lighthouse CI

on:
  pull_request:
  push:
    branches:
      - chore/lighthouse-week1

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true

